### ISSUE TITLE
F20 frontier changed to flux

### ISSUE THREAD

**Issue by kowalskiw** [kowalskiw/mcsteel#1]
`fdsafri.py` converts all frontier constraints to the fluxes, and then 'FISO' to 'LOCAFI'.

Frontier constraints different from FISO should not be converted.

**Comment by kowalskiw** [comment]
Add an exception providing export not FISO frontiers to separate lines.

e.g. 
`F 5 FISO F20 NO NO`
should be converted to:
 `F 5 NO F20 NO NO`
`FLUX 5 LOCAFI NO NO NO`

**Comment by kamil0301** [comment]
#5  Updated in both LCF and CFD:
Not changing frontiers without FISO
If FISO frontier in the same line with F20 frontier, adding them in seperate

**Comment by kowalskiw** [comment]
Ok, I am linking pull request and closing an issue. Thanks!
